# -*- coding: utf-8 -*-
"""Cópia de Jogo da Velha.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1soUpFOi4CQuK4NK9DGkLxBPEqAAfgLMU

# Jogo da Velha

**Etapa1: escreva uma função que possa dar um print no tabuleiro. Seu tabuleiro deve ser representado por uma lista, onde índice (1-9) corresponde a um posição no tabuleiro para termos uma representação de um tabuleiro 3x3 ( Usa a mesma disposição do teclado numérico.**

def display_board(board):
"""

from IPython.display import clear_output

def display_board(board):
    divisoria = '---------'
    for i in range(3):
        print('{} | {} | {}'.format(board[i * 3], board[i * 3 + 1], board[i * 3 + 2]))
        if i < 2:
            print(divisoria)

"""**TESTE da etapa1 :** rode a sua função e faça os ajustes necessários **"""

test_board = [' ',' ',' ',' ',' ',' ',' ',' ',' ',' ']
display_board(test_board)

"""**Etapa 2: Escreva uma função que receba uma entrada do usuário e determine se sua marca será  'X' or 'O'. Sugestão : use while para perguntar continuamente  pela resposta correta.**

 player_input():
"""

def player_input():
    marker=input('Você quer ser X ou O ? ')
    while marker != 'X' and marker != 'O':
        marker=input('Você quer ser X ou O ? ')
    return marker

"""**TESTE Etapa 2:** execute sua função e verifique o funcionamento correto"""

player_input()

"""**Etapa 3: Escreva uma função que receba o tabuleiro, uma marca ('X' ou 'O') e uma posição desejada e atribua esta marca no tabuleiro.**

def place_marker(board, marker, position)
"""

def place_marker(board, marker, position):
      board[position-1] = marker
      display_board(board)

"""**TESTE Etapa 3:** rode a função e veja se elaqfunciona"""

place_marker(test_board,'X',2)

"""**Etapa 4: escreva uma funcção que recebe o tabuleiro e uma marca e verifique se  ganhou. Se ganhou, ela deve retornar True.**

 win_check(board,mark)
"""

def win_check(board,mark):
  possibilidades=[[0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 3, 6], [1, 4, 7], [2, 5, 8], [0, 4, 8], [2, 4, 6]]
  for test in possibilidades:
    if board[test[0]] == board[test[1]] == board[test[2]] == mark:
      return True
  return False

"""**TESTE Etapa 4: rode a função e veja se ela funciona**"""

win_check(test_board,'X')

"""**Etapa 5: Escreva uma função que use o módulo random e decida qual jogador deve ir primeiro. Sugestão: veja a função random.randint(). Retorne uma string de qual jogar deve ir primeiro.**

def choose_first():
"""

import random

def choose_first():
  escolha=random.randint(1,2)
  if escolha == 1:
    print('Jogador 1 deve começar jogando')
  else:
    print('Jogador 2 deve começar jogando')

"""**Etapa 6: escreva uma função que retorne um booleano que retorna se a posição no tabuleiro está livre.**

space_check(board, position)
"""

def space_check(board, position):
    if board[position-1] != ' ':
        return True
    else:
        return False

"""**Etapa 7: escreva uma função que verifica se o tabuleiro está cheio e retorna um boleano. Se estiver cheio , deve retornar True .**



"""

def full_board_check(board):
    for i in range(9):
        if board[i] == ' ':
            return False
    return True

"""**Etapa 8: escreva uma função que pergunte ao jogador pela sua próxima jogada ( posição)  no tabuleiro  um número de 1-9)  e então use a função da etapa 6 para verificar se a posição está livre. Se estiver, retorna a posição para uso futuro.**"""

def player_choice(board):
    choice = int(input('Escolha uma posição para marcar: '))
    while choice>9 or choice<1:
        choice= int(input('O número deve estar na faixa entre 1 e 9. Escolha outro: '))
    while space_check(board, choice):
        choice = int(input('Posição ja foi ocupada, escolha outra: '))
        while choice>9 or choice<1:
            choice = int(input('O número deve estar na faixa entre 1 e 9. Escolha outro: '))
    return choice

"""**Etapa 9:  Escreva uma função que pergunte ao jogador se ele quer jogar de novo e retorne True se ele quiser.**"""

def replay():
    escolha=input('Quer jogar novamente? Responda: S ou N :')
    if escolha == 'S':
        return True
    return False

"""**Etapa 10:  Use while loops e as funções que você fez para rodar o jogo!**"""

print('Jogo da Velha!')
def jogo_da_velha():
    vontade = True
    while vontade:
        #Insere o tabuleiro padrão vazio e informa aos jogadores que o jogo começará.
        tabuleiro=[' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']

        input('\n----------------\nO Jogo da velha será iniciado\nDecida quem será o jogador 1 e o jogador 2\nPressione Enter para prosseguir\n')

        #Define quem jogará primeiro.
        choose_first()

        #O Jogador sorteado escolhe um Simbolo para si.
        marker_1=player_input()
        input('Pressione Enter para Continuar')
        #Define o simbolo do jogador não sorteado.
        if marker_1 == 'X':
            marker_2='O'
        else:
            marker_2='X'
        print('\nPróximo jogador,seu marcador é -> {} <-'.format(marker_2))
        input('Pressione Enter para confirmar')

        print('\nO Jogo irá começar, favor seguir a sequencia correta de jogadas começando pelo jogador sorteado')
        input('Pressione Enter para confirmar o início do jogo')
        while full_board_check(tabuleiro) == False:
            print('\nPrimeiro jogador sorteado: ')
            position1 = player_choice(tabuleiro)
            place_marker(tabuleiro,marker_1,position1)
            if win_check(tabuleiro,marker_1) == True:
                input('VOCÊ GANHOU! Pressione enter para continuar')
                break
            if full_board_check(tabuleiro) == True:
                break
            input('\nPressione Enter para proxima jogada')
            print('\nSegundo jogador sorteado: ')
            position2 = player_choice(tabuleiro)
            place_marker(tabuleiro, marker_2, position2)
            if win_check(tabuleiro, marker_2) == True:
                input('VOCÊ GANHOU! Pressione enter para continuar')
                break
            input('\nPressione Enter para proxima jogada')
        vontade = replay()

jogo_da_velha()